# Generated by Django 4.0.2 on 2022-04-30 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("levels", "0007_alter_level_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Walkthrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True
                    ),
                ),
                (
                    "legacy_author_name",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("is_pending_approval", models.BooleanField(default=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "walkthrough_type",
                    models.CharField(
                        choices=[("l", "Link"), ("t", "Text")], max_length=3
                    ),
                ),
                ("text", models.TextField(max_length=50000)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_walkthroughs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="levels.level",
                        related_name="walkthroughs",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
