# Generated by Django 4.0.2 on 2022-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walkthroughs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkthrough",
            name="status",
            field=models.CharField(
                choices=[
                    ("dra", "Draft"),
                    ("pen", "Pending approval"),
                    ("app", "Approved"),
                    ("rej", "Rejected"),
                ],
                default="dra",
                max_length=3,
            ),
        ),
    ]
