# Generated by Django 4.0.2 on 2022-05-05 17:56

from django.db import migrations


def update_walkthroughs_forward(apps, schema_editor):
    Walkthrough = apps.get_model("walkthroughs", "Walkthrough")
    for walkthrough in Walkthrough.objects.iterator():
        if walkthrough.is_pending_approval:
            walkthrough.status = "pen"
        elif walkthrough.is_approved:
            walkthrough.status = "app"
        else:
            walkthrough.status = "rej"
        walkthrough.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("walkthroughs", "0002_add_status"),
    ]

    operations = [
        migrations.RunPython(
            update_walkthroughs_forward, migrations.RunPython.noop
        ),
    ]
