# Generated by Django 4.0.2 on 2022-05-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("walkthroughs", "0003_port_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walkthrough",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="walkthrough",
            name="is_pending_approval",
        ),
    ]
