# Generated by Django 4.0.2 on 2022-05-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walkthroughs", "0004_remove_walkthrough_is_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walkthrough",
            name="text",
            field=models.TextField(),
        ),
    ]
