# Generated by Django 4.0.2 on 2022-07-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walkthroughs", "0005_alter_walkthrough_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walkthrough",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
