# Generated by Django 4.2.3 on 2024-11-12 12:09

from django.db import migrations


def update_walkthroughs_foward(apps, schema_editor):
    batch_size = 1000
    Walkthrough = apps.get_model("walkthroughs", "Walkthrough")

    qs = Walkthrough.objects.all().values_list("id", "created")
    while True:
        batch = list(qs[:batch_size])
        if not batch:
            break

        update_list = [
            Walkthrough(id=id, last_user_content_updated=created)
            for id, created in batch
        ]
        Walkthrough.objects.bulk_update(
            update_list, ["last_user_content_updated"]
        )
        qs = qs[batch_size:]


class Migration(migrations.Migration):

    dependencies = [
        ("walkthroughs", "0007_walkthrough_last_user_content_updated"),
    ]

    operations = [
        migrations.RunPython(
            update_walkthroughs_foward,
            migrations.RunPython.noop,
        ),
    ]
