# Generated by Django 4.0 on 2022-03-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="trle_author_id",
            field=models.IntegerField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="trle_reviewer_id",
            field=models.IntegerField(blank=True, max_length=32, null=True),
        ),
    ]
