# Generated by Django 4.0 on 2022-03-15 08:09

from django.contrib.auth.hashers import make_password
from django.db import migrations


def update_users_forward(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.filter(source="trle").iterator():
        user.password = make_password(None)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_trle_author_id_and_more"),
    ]

    operations = [
        migrations.RunPython(update_users_forward, migrations.RunPython.noop),
    ]
