# Generated by Django 4.0 on 2022-03-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20220315_0809"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="trle_author_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="trle_reviewer_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
