# Generated by Django 4.0 on 2022-03-24 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_trle_author_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": [],
                "permissions": [
                    ("edit_levels", "Can edit levels"),
                    ("edit_reviews", "Can edit reviews"),
                    ("edit_tags", "Can edit tags"),
                    ("edit_news", "Can edit news"),
                    ("edit_users", "Can edit users"),
                    ("list_users", "Can list users"),
                    ("view_users", "Can view users"),
                    ("review_audit_logs", "Can review audit logs"),
                    ("review_levels", "Can review levels"),
                    ("upload_levels", "Can upload levels"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
