# Generated by Django 4.0.2 on 2022-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="authored_level_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="reviewed_level_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
