# Generated by Django 4.0.2 on 2022-04-08 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_authored_level_count_user_reviewed_level_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": [],
                "permissions": [
                    ("delete_levels", "Can delete levels"),
                    ("delete_reviews", "Can delete reviews"),
                    ("edit_levels", "Can edit levels"),
                    ("edit_reviews", "Can edit reviews"),
                    ("edit_tags", "Can edit tags"),
                    ("edit_news", "Can edit news"),
                    ("edit_users", "Can edit users"),
                    ("manage_users", "Can manage users"),
                    ("list_users", "Can list users"),
                    ("view_users", "Can view users"),
                    ("review_audit_logs", "Can review audit logs"),
                    ("review_levels", "Can review levels"),
                    ("upload_levels", "Can upload levels"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
