# Generated by Django 4.0.2 on 2022-04-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="website_url",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
