# Generated by Django 4.0.2 on 2022-04-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="donation_url",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
