# Generated by Django 4.0.2 on 2022-04-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_donation_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="authored_walkthrough_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
