# Generated by Django 4.0.2 on 2022-07-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ban_reason",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
