# Generated by Django 4.2.3 on 2024-11-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_played_level_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rated_level_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
