# Generated by Django 4.2.3 on 2024-11-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="authored_level_count",
            new_name="authored_level_count_all",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="authored_walkthrough_count",
            new_name="authored_walkthrough_count_all",
        ),
        migrations.AddField(
            model_name="user",
            name="authored_level_count_approved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="authored_walkthrough_count_approved",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
