"""
Generated by Django on add email settings model for user preferences.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = False

    dependencies = [
        (
            "users",
            "0019_rename_authored_level_count_user_authored_level_"
            "count_all_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_review_posted", models.BooleanField(default=True)),
                ("email_rating_posted", models.BooleanField(default=True)),
                (
                    "email_walkthrough_posted",
                    models.BooleanField(default=True),
                ),
                ("email_review_updated", models.BooleanField(default=False)),
                ("email_rating_updated", models.BooleanField(default=False)),
                (
                    "email_walkthrough_updated",
                    models.BooleanField(default=False),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=models.CASCADE,
                        related_name="settings",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
