# Generated by Django 4.2.3 on 2025-05-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_user_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
