# Generated by Django 4.2.3 on 2025-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_usersettings_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
