# Generated by Django 4.2.3 on 2025-09-21 13:18

from django.db import migrations


def update_forward(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(is_active=False).update(date_joined=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_user_date_joined"),
    ]

    operations = [
        migrations.RunPython(update_forward, migrations.RunPython.noop),
    ]
