# Generated by Django 4.0 on 2022-03-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("code", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="RatingClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("le", "Level"), ("re", "Review")],
                        max_length=2,
                    ),
                ),
                ("position", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=30)),
                ("min_rating_count", models.IntegerField()),
                (
                    "min_rating_average",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "max_rating_average",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rating classes",
                "ordering": ["position"],
                "default_permissions": [],
            },
        ),
    ]
