# Generated by Django 4.0 on 2022-03-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"default_permissions": []},
        ),
    ]
