# Generated by Django 4.2.3 on 2024-11-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_country_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingclass",
            name="target",
            field=models.CharField(
                choices=[("le", "Level"), ("ra", "Rating")], max_length=2
            ),
        ),
    ]
