version: '3.7'

x-backend-environment: &base-backend-environment
  - SECRET_KEY=${SECRET_KEY}
  - DEBUG=${DEBUG}
  - HOST_SITE=${HOST_SITE}
  - POSTGRES_DB=trcustoms
  - POSTGRES_USER=root
  - POSTGRES_PASSWORD=root
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_STORAGE_BUCKET_NAME
  - USE_AWS_STORAGE
  - EMAIL_HOST
  - EMAIL_PORT
  - EMAIL_HOST_USER
  - EMAIL_HOST_PASSWORD
  - EMAIL_USE_TLS
  - EMAIL_USE_SSL

x-base-trcustoms: &base-trcustoms
  restart: unless-stopped

x-base-trcustoms-backend: &base-trcustoms-backend
  <<: *base-trcustoms
  environment: *base-backend-environment
  build:
    context: .
    dockerfile: ./services/backend/Dockerfile
  volumes:
    - ./backend/trcustoms/:/app/trcustoms/
    - ./backend/volumes/cache/:/app/cache/
    - ./backend/volumes/uploads/:/app/uploads/
    - ./backend/volumes/django_static/:/app/django_static/
    - ./services/backend/entrypoint.sh:/usr/local/bin/entrypoint.sh
    - ./pyproject.toml:/pyproject.toml
    - /tmp:/tmp
  networks:
    - trcustoms
  depends_on:
    - trcustoms-redis
    - trcustoms-db
    - trcustoms-mailhog

services:
  trcustoms:
    <<: *base-trcustoms-backend
    container_name: trcustoms_dev_backend
    command: dev

  trcustoms-celery:
    <<: *base-trcustoms-backend
    container_name: trcustoms_dev_celery
    command: celery

  trcustoms-celery-beat:
    <<: *base-trcustoms-backend
    container_name: trcustoms_dev_celery_beat
    command: celery-beat

  trcustoms-frontend:
    <<: *base-trcustoms
    container_name: trcustoms_dev_frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
    volumes:
      - ./frontend/public/:/app/public/
      - ./frontend/src/:/app/src/
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./services/frontend/entrypoint.sh:/usr/local/bin/entrypoint.sh
    networks:
      - trcustoms
    depends_on:
      - trcustoms
    command: dev
    ports:
      - '3000:3000'

  trcustoms-db:
    <<: *base-trcustoms
    container_name: trcustoms_dev_db
    image: postgres:14.0
    environment: *base-backend-environment
    expose:
      - 5432
    volumes:
      - ./backend/volumes/pgdata:/var/lib/postgresql/data
    networks:
      - trcustoms

  trcustoms-redis:
    <<: *base-trcustoms
    container_name: trcustoms_dev_redis
    image: redis:6
    expose:
      - 6379
    networks:
      - trcustoms

  nginx:
    <<: *base-trcustoms
    container_name: trcustoms_dev_nginx
    image: nginx
    volumes:
      - ./services/nginx/nginx_dev.conf:/etc/nginx/nginx.conf:ro
      - ./backend/volumes/uploads/:/app/uploads/
      - ./backend/volumes/django_static/:/app/django_static/
    command: ['nginx', '-g', 'daemon off;']
    networks:
      - trcustoms
    ports:
      - mode: host
        protocol: tcp
        published: ${TRCUSTOMS_PORT}
        target: 8000
    depends_on:
      - trcustoms

  trcustoms-mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: trcustoms_dev_mailhog
    expose:
      - 1025
    networks:
      - trcustoms
    ports:
      - '8025:8025'

networks:
  trcustoms:
    external: false
