version: "3.7"

x-backend-environment: &base-backend-environment
  - SECRET_KEY=${SECRET_KEY}
  - DEBUG=0
  - DEBUG_SQL=0
  - HOST_SITE=${HOST_SITE}
  - POSTGRES_DB=trcustoms
  - POSTGRES_USER=root
  - POSTGRES_PASSWORD=root
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_STORAGE_BUCKET_NAME
  - AWS_S3_ENDPOINT_URL
  - AWS_S3_CUSTOM_DOMAIN
  - USE_AWS_STORAGE
  - EMAIL_HOST
  - EMAIL_PORT
  - EMAIL_HOST_USER
  - EMAIL_HOST_PASSWORD
  - EMAIL_USE_TLS
  - EMAIL_USE_SSL

x-base-trcustoms: &base-trcustoms
  restart: always

x-base-trcustoms-backend: &base-trcustoms-backend
  <<: *base-trcustoms
  environment: *base-backend-environment
  build:
    context: .
    dockerfile: ./services/backend/Dockerfile
    args:
      - BUILD_DATE=${BUILD_DATE}
      - BUILD_VERSION=${BUILD_VERSION}
  volumes:
    - ./backend/trcustoms/:/app/trcustoms/
    - ./backend/volumes/cache/:/app/cache/
    - ./backend/volumes/uploads/:/app/uploads/
    - ./backend/volumes/django_static/:/app/django_static/
    - ./services/backend/entrypoint.sh:/usr/local/bin/entrypoint.sh
    - ./pyproject.toml:/pyproject.toml
    - /tmp:/tmp
  networks:
    - trcustoms
  depends_on:
    - trcustoms-redis
    - trcustoms-db

services:
  trcustoms:
    <<: *base-trcustoms-backend
    container_name: trcustoms_prd_backend
    command: uwsgi

  trcustoms-celery:
    <<: *base-trcustoms-backend
    container_name: trcustoms_prd_celery
    command: celery

  trcustoms-celery-beat:
    <<: *base-trcustoms-backend
    container_name: trcustoms_prd_celery_beat
    command: celery-beat

  trcustoms-db:
    <<: *base-trcustoms
    container_name: trcustoms_prd_db
    image: postgres:14.0
    environment: *base-backend-environment
    expose:
      - 5432
    volumes:
      - ./backend/volumes/pgdata:/var/lib/postgresql/data
    networks:
      - trcustoms

  trcustoms-redis:
    <<: *base-trcustoms
    container_name: trcustoms_prd_redis
    image: redis:6
    expose:
      - 6379
    networks:
      - trcustoms

  trcustoms-nginx:
    <<: *base-trcustoms
    container_name: trcustoms_prd_nginx
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile_prod
      args:
        - BUILD_DATE=${BUILD_DATE}
        - BUILD_VERSION=${BUILD_VERSION}
    networks:
      - trcustoms
    ports:
      - mode: host
        protocol: tcp
        published: ${TRCUSTOMS_PORT}
        target: 8000
    depends_on:
      - trcustoms
    volumes:
      - ./backend/volumes/django_static:/app/backend/django_static
      - ./backend/volumes/uploads:/app/backend/django_uploads

networks:
  trcustoms:
    external: false
