[project]
name = "trcustoms"
version = "0.0.0"
description = "A website dedicated to custom levels for classic Tomb Raider games."
requires-python = ">=3.11"
dependencies = [
    "Django>=5.2,<5.3",
    "django-extensions>=3.2.3",
    "djangorestframework>=3.16",
    "djangorestframework-simplejwt>=5.4",
    "uWSGI>=2.0.28",
    "celery>=5.4",
    "django-redis>=5.4",
    "psycopg2>=2.9.10",
    "Pillow>=11.0",
    "python-magic>=0.4.27",
    "requests>=2.32.2",
    "cssselect>=1.2",
    "lxml>=5.3",
    "pyyaml>=6.0.2",
    "markdownify>=0.13",
    "django-unused-media>=0.2.2",
    "django-cleanup>=8.1",
    "unidecode>=1.3.8",
    "boto3>=1.35",
    "django-storages>=1.14.4",
    "premailer>=3.10",
    "tqdm>=4.66.3",
    "numpy>=1.26,<2",
    "drf-spectacular>=0.28",
]

[dependency-groups]
dev = [
    "pytest>=8",
    "pytest-cov",
    "pytest-django",
    "pytest-factoryboy",
    "pytest-profiling",
    "pytest-lazy-fixtures",
    "factory-boy",
    "mimesis",
    "pytest-xdist",
]

[tool.uv]
package = false

[tool.black]
line-length = 79
target-version = ["py310"]

[tool.ruff]
line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["trcustoms"]

[tool.pylint.master]
jobs = 0

[tool.pylint.format]
max-line-length = 79

[tool.pylint.messages_control]
reports = "no"
disable = [
    "import-error",
    "too-few-public-methods",
    "use-dict-literal",
    "missing-docstring",
    "unused-argument",  # we can't rename positional arguments in frameworks…
    "duplicate-code",  # false positives in imports…
    "invalid-name",  # migrations
    "too-many-instance-attributes",  # models
    "too-many-arguments",  # pytest fixtures
    "too-many-positional-arguments",  # pytest fixtures
    "too-many-locals",  # pytest fixtures
    "broad-except",  # this does more harm than good
    "unexpected-keyword-arg",  # badly implemented in decorators…
    "unsupported-binary-operation",  # fails to handle DRF permissions…
    "protected-access", # _meta
    "too-many-ancestors",  # how else am I supposed to use DRF mixins
    "fixme",  # my time is too precious to deal with everything at once
    "consider-iterating-dictionary",  # useless advice
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "trcustoms.settings"
norecursedirs = [
    "cache",
    "pgdata",
    "uploads",
]
