[tool.black]
line-length = 79
target-version = ["py310"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true

[tool.pylint.master]
jobs = 0

[tool.pylint.format]
max-line-length = 79

[tool.pylint.messages_control]
reports = "no"
disable = [
    "import-error",
    "too-few-public-methods",
    "no-self-use",
    "missing-docstring",
    "unused-argument",  # we can't rename positional arguments in frameworks…
    "duplicate-code",  # false positives in imports…
    "invalid-name",  # migrations
    "too-many-instance-attributes",  # models
    "too-many-arguments",  # pytest fixtures
    "too-many-locals",  # pytest fixtures
    "broad-except",  # this does more harm than good
    "unexpected-keyword-arg",  # badly implemented in decorators…
    "unsupported-binary-operation",  # fails to handle DRF permissions…
    "protected-access", # _meta
    "fixme",  # my time is too precious to deal with everything at once
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "trcustoms.settings"
norecursedirs = [
    "cache",
    "pgdata",
    "uploads",
]
