// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AuditLogListing = {
    readonly id: number;
    readonly created: string | null;
    object_id: string;
    object_name: string;
    readonly object_type: string;
    change_type: ChangeTypeEnum;
    change_author: UserNested;
    changes: unknown;
    meta: unknown;
    is_action_required?: boolean;
};

export type AwardRecipient = {
    user: UserNested;
    readonly created: string | null;
    readonly last_updated: string | null;
    readonly awarded_on: string | null;
};

export type AwardSpec = {
    code: string;
    title: string;
    description: string;
    readonly guide_description: string;
    tier: number;
    can_be_removed: boolean;
    readonly rarity: number;
    readonly user_percentage: number;
};

/**
 * * `CREATE` - Create
 * * `UPDATE` - Update
 * * `DELETE` - Delete
 */
export type ChangeTypeEnum = 'CREATE' | 'UPDATE' | 'DELETE';

export type Config = {
    countries: Array<CountryListing>;
    tags: Array<TagListing>;
    genres: Array<GenreListing>;
    engines: Array<EngineListing>;
    difficulties: Array<LevelDifficultyListing>;
    durations: Array<LevelDurationListing>;
    rating_questions: Array<RatingTemplateQuestion>;
    limits: GlobalLimits;
    stats: GlobalStats;
    global_message?: string | null;
};

export type CountryListing = {
    iso_3166_1_alpha2: string;
    name: string;
    iso_3166_1_numeric?: string | null;
};

export type CountryNested = {
    iso_3166_1_alpha2: string;
    name: string;
    iso_3166_1_numeric?: string | null;
};

export type EngineListing = {
    readonly id: number;
    name: string;
    position?: number;
    readonly level_count: number;
    readonly created: string | null;
    readonly last_updated: string | null;
};

export type EngineNested = {
    readonly id: number;
    name: string;
};

export type EventDetails = {
    readonly id: number;
    name: string;
    subtitle?: string | null;
    cover_image: UploadedFileNested;
    year?: number | null;
    readonly level_count: number;
    readonly created: string | null;
    readonly last_updated: string | null;
    readonly about: string;
    host: UserNested;
    readonly winners: Array<Winner>;
    readonly levels: Array<LevelListing>;
};

export type EventListing = {
    readonly id: number;
    name: string;
    subtitle?: string | null;
    cover_image: UploadedFileNested;
    year?: number | null;
    readonly level_count: number;
    readonly created: string | null;
    readonly last_updated: string | null;
};

/**
 * * `new_release` - New release
 * * `monthly_hidden_gem` - Monthly hidden gem
 * * `level_of_the_day` - Level of the day
 * * `best_in_genre` - Best in genre
 */
export type FeatureTypeEnum = 'new_release' | 'monthly_hidden_gem' | 'level_of_the_day' | 'best_in_genre';

export type FeaturedLevelListing = {
    readonly created: string | null;
    feature_type: FeatureTypeEnum;
    level: LevelListing;
    chosen_genre: GenreNested;
};

export type FeaturedLevels = {
    new_release: FeaturedLevelListing;
    monthly_hidden_gem: FeaturedLevelListing;
    level_of_the_day: FeaturedLevelListing;
    best_in_genre: FeaturedLevelListing;
};

export type GenreListing = {
    readonly id: number;
    name: string;
    description: string;
    readonly level_count: number;
    readonly created: string | null;
    readonly last_updated: string | null;
};

export type GenreNested = {
    readonly id: number;
    name: string;
};

export type GlobalLimits = {
    min_genres: number;
    max_genres: number;
    min_tags: number;
    max_tags: number;
    min_screenshots: number;
    max_screenshots: number;
    min_showcase_links: number;
    max_showcase_links: number;
    min_authors: number;
    max_authors: number;
    max_tag_length: number;
    markdown_fields: {
        [key: string]: number | null;
    };
};

export type GlobalStats = {
    total_levels: number;
    total_ratings: number;
    total_reviews: number;
    total_walkthroughs: number;
    total_downloads: number;
    ratings: Array<RatingStat>;
    walkthroughs: WalkthroughStat;
};

export type LevelCategoryRatings = {
    category: string;
    total_points: number;
    min_points: number;
    max_points: number;
};

export type LevelDetails = {
    readonly id: number;
    name: string;
    description: string;
    engine: EngineNested;
    duration: LevelDurationNested;
    difficulty: LevelDifficultyNested;
    readonly genres: Array<GenreNested>;
    readonly tags: Array<TagNested>;
    readonly authors: Array<UserNested>;
    uploader: UserNested;
    readonly created: string | null;
    cover: UploadedFileNested;
    readonly screenshots: Array<LevelScreenshot>;
    external_links?: Array<LevelExternalLink>;
    readonly last_updated: string | null;
    readonly last_user_content_updated: string | null;
    last_file: LevelFile;
    readonly download_count: number;
    readonly rating_count: number;
    readonly review_count: number;
    readonly walkthrough_count: number;
    readonly is_approved: boolean;
    readonly rejection_reason: string | null;
    rating_class: RatingClassNested;
    readonly files: Array<LevelFile>;
    trle_id?: number | null;
};

export type LevelDifficultyListing = {
    readonly id: number;
    name: string;
    position: number;
    readonly created: string | null;
    readonly last_updated: string | null;
};

export type LevelDifficultyNested = {
    readonly id: number;
    name: string;
};

export type LevelDurationListing = {
    readonly id: number;
    name: string;
    position: number;
    readonly created: string | null;
    readonly last_updated: string | null;
};

export type LevelDurationNested = {
    readonly id: number;
    name: string;
};

export type LevelExternalLink = {
    readonly id: number;
    position: number;
    url: string;
    link_type: LinkTypeEnum;
};

export type LevelFile = {
    readonly id: number;
    version: number;
    readonly size: number | null;
    readonly created: string | null;
    readonly url: string | null;
};

export type LevelListing = {
    readonly id: number;
    name: string;
    description?: string | null;
    engine: EngineNested;
    duration: LevelDurationNested;
    difficulty: LevelDifficultyNested;
    readonly genres: Array<GenreNested>;
    readonly tags: Array<TagNested>;
    readonly authors: Array<UserNested>;
    uploader: UserNested;
    readonly created: string | null;
    cover: UploadedFileNested;
    readonly screenshots: Array<LevelScreenshot>;
    external_links?: Array<LevelExternalLink>;
    readonly last_updated: string | null;
    readonly last_user_content_updated: string | null;
    last_file: LevelFile;
    readonly download_count: number;
    readonly rating_count: number;
    readonly review_count: number;
    readonly walkthrough_count: number;
    readonly is_approved: boolean;
    readonly rejection_reason: string | null;
    rating_class: RatingClassNested;
};

export type LevelNested = {
    readonly id: number;
    name: string;
    cover: UploadedFileNested;
};

export type LevelRatingStats = {
    trc_rating_count: number;
    trle_rating_count: number;
    categories: Array<LevelCategoryRatings>;
};

export type LevelRejection = {
    reason: string;
};

export type LevelScreenshot = {
    readonly id: number;
    position?: number;
    file: UploadedFileNested;
};

/**
 * * `sh` - Showcase
 * * `ma` - Main
 */
export type LinkTypeEnum = 'sh' | 'ma';

export type NewsDetails = {
    readonly id: number;
    subject?: string | null;
    text?: string | null;
    readonly created: string | null;
    readonly last_updated: string | null;
};

export type NewsListing = {
    readonly id: number;
    subject?: string | null;
    text?: string | null;
    readonly created: string | null;
    readonly last_updated: string | null;
};

export type PaginatedAuditLogListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<AuditLogListing>;
    disable_paging: boolean;
};

export type PaginatedAwardRecipientList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<AwardRecipient>;
    disable_paging: boolean;
};

export type PaginatedEngineListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<EngineListing>;
    disable_paging: boolean;
};

export type PaginatedEventListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<EventListing>;
    disable_paging: boolean;
};

export type PaginatedGenreListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<GenreListing>;
    disable_paging: boolean;
};

export type PaginatedLevelListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<LevelListing>;
    disable_paging: boolean;
};

export type PaginatedNewsListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<NewsListing>;
    disable_paging: boolean;
};

export type PaginatedPlaylistItemList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<PlaylistItem>;
    disable_paging: boolean;
};

export type PaginatedRatingListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<RatingListing>;
    disable_paging: boolean;
};

export type PaginatedReviewListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<ReviewListing>;
    disable_paging: boolean;
};

export type PaginatedTagListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<TagListing>;
    disable_paging: boolean;
};

export type PaginatedUserListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<UserListing>;
    disable_paging: boolean;
};

export type PaginatedWalkthroughListingList = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<WalkthroughListing>;
    disable_paging: boolean;
};

export type PatchedLevelDetails = {
    readonly id?: number;
    name?: string;
    description?: string;
    engine?: EngineNested;
    duration?: LevelDurationNested;
    difficulty?: LevelDifficultyNested;
    readonly genres?: Array<GenreNested>;
    readonly tags?: Array<TagNested>;
    readonly authors?: Array<UserNested>;
    uploader?: UserNested;
    readonly created?: string | null;
    cover?: UploadedFileNested;
    readonly screenshots?: Array<LevelScreenshot>;
    external_links?: Array<LevelExternalLink>;
    readonly last_updated?: string | null;
    readonly last_user_content_updated?: string | null;
    last_file?: LevelFile;
    readonly download_count?: number;
    readonly rating_count?: number;
    readonly review_count?: number;
    readonly walkthrough_count?: number;
    readonly is_approved?: boolean;
    readonly rejection_reason?: string | null;
    rating_class?: RatingClassNested;
    readonly files?: Array<LevelFile>;
    trle_id?: number | null;
};

export type PatchedNewsDetails = {
    readonly id?: number;
    subject?: string | null;
    text?: string | null;
    readonly created?: string | null;
    readonly last_updated?: string | null;
};

export type PatchedPlaylistItem = {
    readonly id?: number;
    level?: LevelNested;
    user?: UserNested;
    status?: PlaylistItemStatusEnum;
    readonly created?: string | null;
    readonly last_updated?: string | null;
};

export type PatchedRatingDetails = {
    readonly id?: number;
    author?: RatingAuthor;
    level?: LevelNested;
    readonly created?: string | null;
    rating_type?: RatingTypeEnum;
    readonly last_updated?: string | null;
    rating_class?: RatingClassNested;
    readonly last_user_content_updated?: string | null;
    readonly answers?: Array<number>;
};

export type PatchedReviewDetails = {
    readonly id?: number;
    author?: ReviewAuthor;
    level?: LevelNested;
    text?: string;
    is_hidden?: boolean;
    rejection_reason?: string | null;
    readonly created?: string | null;
    readonly last_updated?: string | null;
    readonly last_user_content_updated?: string | null;
    upvote_count?: number;
    downvote_count?: number;
    readonly current_user_vote?: number | null;
    readonly can_vote?: boolean;
};

export type PatchedTagDetails = {
    readonly id?: number;
    name?: string;
    readonly level_count?: number;
    readonly created?: string | null;
    readonly last_updated?: string | null;
};

export type PatchedUserDetails = {
    readonly id?: number;
    username?: string;
    first_name?: string;
    last_name?: string;
    bio?: string;
    readonly date_joined?: string | null;
    readonly last_login?: string | null;
    /**
     * Active
     *
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    readonly is_active?: boolean;
    readonly is_banned?: boolean;
    readonly is_pending_activation?: boolean;
    readonly played_level_count?: number;
    readonly authored_level_count_all?: number;
    readonly authored_level_count_approved?: number;
    readonly authored_walkthrough_count_all?: number;
    readonly authored_walkthrough_count_approved?: number;
    readonly rated_level_count?: number;
    readonly reviewed_level_count?: number;
    picture?: UploadedFileNested;
    readonly permissions?: Array<string>;
    readonly trle_reviewer_id?: number | null;
    readonly trle_author_id?: number | null;
    email?: string;
    country?: CountryNested;
    website_url?: string | string | null;
    donation_url?: string | string | null;
    /**
     * Staff status
     *
     * Designates whether the user can log into this admin site.
     */
    readonly is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly is_superuser?: boolean;
    settings?: UserSettings;
    readonly awards?: Array<UserAward>;
};

export type PatchedWalkthroughDetails = {
    readonly id?: number;
    level?: LevelNested;
    author?: WalkthroughAuthor;
    readonly legacy_author_name?: string | null;
    status?: StatusAa3Enum;
    readonly rejection_reason?: string | null;
    walkthrough_type?: WalkthroughTypeEnum;
    text?: string;
    readonly created?: string | null;
    readonly last_updated?: string | null;
    readonly last_user_content_updated?: string | null;
};

export type PlaylistImportResult = {
    updated_items: number;
};

export type PlaylistItem = {
    readonly id: number;
    level: LevelNested;
    user: UserNested;
    status: PlaylistItemStatusEnum;
    readonly created: string | null;
    readonly last_updated: string | null;
};

/**
 * * `not_yet_played` - Not yet played
 * * `playing` - Playing
 * * `finished` - Finished
 * * `dropped` - Dropped
 * * `on_hold` - On hold
 */
export type PlaylistItemStatusEnum = 'not_yet_played' | 'playing' | 'finished' | 'dropped' | 'on_hold';

export type RatingAuthor = {
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
    picture: UploadedFileNested;
    rated_level_count?: number;
};

export type RatingClassNested = {
    readonly id: number;
    name: string;
    position?: number | null;
};

export type RatingDetails = {
    readonly id: number;
    author: RatingAuthor;
    level: LevelNested;
    readonly created: string | null;
    rating_type: RatingTypeEnum;
    readonly last_updated: string | null;
    rating_class: RatingClassNested;
    readonly last_user_content_updated: string | null;
    readonly answers: Array<number>;
};

export type RatingListing = {
    readonly id: number;
    author: RatingAuthor;
    level: LevelNested;
    readonly created: string | null;
    rating_type: RatingTypeEnum;
    readonly last_updated: string | null;
    rating_class: RatingClassNested;
    readonly last_user_content_updated: string | null;
};

export type RatingStat = {
    rating_class: RatingClassNested;
    level_count: number;
};

export type RatingTemplateAnswer = {
    readonly id: number;
    position: number;
    answer_text: string;
};

export type RatingTemplateQuestion = {
    readonly id: number;
    position: number;
    question_text: string;
    readonly answers: Array<RatingTemplateAnswer>;
    category?: string | null;
};

/**
 * * `le` - Legacy (TRLE.net)
 * * `mo` - Modern (TRCustoms)
 */
export type RatingTypeEnum = 'le' | 'mo';

export type ReviewAuthor = {
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
    picture: UploadedFileNested;
    reviewed_level_count?: number;
};

export type ReviewDetails = {
    readonly id: number;
    author: ReviewAuthor;
    level: LevelNested;
    text: string;
    is_hidden?: boolean;
    rejection_reason?: string | null;
    readonly created: string | null;
    readonly last_updated: string | null;
    readonly last_user_content_updated: string | null;
    upvote_count?: number;
    downvote_count?: number;
    readonly current_user_vote: number | null;
    readonly can_vote: boolean;
};

export type ReviewHide = {
    reason: string;
};

export type ReviewListing = {
    readonly id: number;
    author: ReviewAuthor;
    level: LevelNested;
    text?: string | null;
    is_hidden?: boolean;
    rejection_reason?: string | null;
    readonly created: string | null;
    readonly last_updated: string | null;
    readonly last_user_content_updated: string | null;
    upvote_count?: number;
    downvote_count?: number;
    readonly current_user_vote: number | null;
    readonly can_vote: boolean;
};

export type ReviewVote = {
    vote: VoteEnum;
};

/**
 * * `dra` - Draft
 * * `pen` - Pending approval
 * * `app` - Approved
 * * `rej` - Rejected
 */
export type StatusAa3Enum = 'dra' | 'pen' | 'app' | 'rej';

export type TagDetails = {
    readonly id: number;
    name: string;
    readonly level_count: number;
    readonly created: string | null;
    readonly last_updated: string | null;
};

export type TagListing = {
    readonly id: number;
    name: string;
    readonly level_count: number;
    readonly created: string | null;
    readonly last_updated: string | null;
};

export type TagMerge = {
    target_tag_id: number;
};

export type TagNested = {
    readonly id: number;
    name: string;
};

export type TokenBlacklist = {
    refresh: string;
};

export type TokenObtainPair = {
    username: string;
    password: string;
    readonly access: string;
    readonly refresh: string;
};

export type TokenRefresh = {
    readonly access: string;
    refresh: string;
};

/**
 * * `up` - User picture
 * * `lb` - Level cover image
 * * `ls` - Level screenshot
 * * `lf` - Level file
 * * `at` - Post attachment
 * * `ec` - Event cover image
 */
export type UploadTypeEnum = 'up' | 'lb' | 'ls' | 'lf' | 'at' | 'ec';

export type UploadedFileDetails = {
    readonly id: number;
    content?: string | null;
    upload_type: UploadTypeEnum;
    readonly url: string | null;
    readonly size: number;
    readonly md5sum: string | null;
};

export type UploadedFileNested = {
    readonly id: number;
    content?: string | null;
    upload_type: UploadTypeEnum;
    readonly url: string | null;
    readonly size: number;
    readonly md5sum: string | null;
};

export type UserAward = {
    readonly created: string | null;
    readonly last_updated: string | null;
    position?: number;
    code: string;
    title: string;
    description: string;
    tier?: number | null;
    readonly rarity: number;
    readonly user_percentage: number;
};

export type UserBan = {
    reason: string;
};

export type UserCompletePasswordReset = {
    token: string;
};

export type UserConfirmEmail = {
    token: string;
};

export type UserDetails = {
    readonly id: number;
    username: string;
    first_name?: string;
    last_name?: string;
    bio?: string;
    readonly date_joined: string | null;
    readonly last_login: string | null;
    /**
     * Active
     *
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    readonly is_active: boolean;
    readonly is_banned: boolean;
    readonly is_pending_activation: boolean;
    readonly played_level_count: number;
    readonly authored_level_count_all: number;
    readonly authored_level_count_approved: number;
    readonly authored_walkthrough_count_all: number;
    readonly authored_walkthrough_count_approved: number;
    readonly rated_level_count: number;
    readonly reviewed_level_count: number;
    picture: UploadedFileNested;
    readonly permissions: Array<string>;
    readonly trle_reviewer_id: number | null;
    readonly trle_author_id: number | null;
    email: string;
    country: CountryNested;
    website_url?: string | string | null;
    donation_url?: string | string | null;
    /**
     * Staff status
     *
     * Designates whether the user can log into this admin site.
     */
    readonly is_staff: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly is_superuser: boolean;
    settings?: UserSettings;
    readonly awards: Array<UserAward>;
};

export type UserListing = {
    readonly id: number;
    username: string;
    first_name?: string;
    last_name?: string;
    bio?: string;
    readonly date_joined: string | null;
    readonly last_login: string | null;
    /**
     * Active
     *
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    readonly is_active: boolean;
    readonly is_banned: boolean;
    readonly is_pending_activation: boolean;
    readonly played_level_count: number;
    readonly authored_level_count_all: number;
    readonly authored_level_count_approved: number;
    readonly authored_walkthrough_count_all: number;
    readonly authored_walkthrough_count_approved: number;
    readonly rated_level_count: number;
    readonly reviewed_level_count: number;
    picture: UploadedFileNested;
    readonly permissions: Array<string>;
    readonly trle_reviewer_id: number | null;
    readonly trle_author_id: number | null;
};

export type UserNested = {
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
    picture: UploadedFileNested;
};

export type UserRequestPasswordReset = {
    email: string;
};

export type UserSettings = {
    email_review_posted?: boolean;
    email_rating_posted?: boolean;
    email_walkthrough_posted?: boolean;
    email_review_updated?: boolean;
    email_rating_updated?: boolean;
    email_walkthrough_updated?: boolean;
};

export type Username = {
    username: string;
};

/**
 * * `-1` - -1
 * * `1` - 1
 */
export type VoteEnum = -1 | 1;

export type WalkthroughAuthor = {
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
    picture: UploadedFileNested;
};

export type WalkthroughDetails = {
    readonly id: number;
    level: LevelNested;
    author: WalkthroughAuthor;
    readonly legacy_author_name: string | null;
    status: StatusAa3Enum;
    readonly rejection_reason: string | null;
    walkthrough_type: WalkthroughTypeEnum;
    text: string;
    readonly created: string | null;
    readonly last_updated: string | null;
    readonly last_user_content_updated: string | null;
};

export type WalkthroughListing = {
    readonly id: number;
    level: LevelNested;
    author: WalkthroughAuthor;
    readonly legacy_author_name: string | null;
    status: StatusAa3Enum;
    readonly rejection_reason: string | null;
    walkthrough_type: WalkthroughTypeEnum;
    text: string;
    readonly created: string | null;
    readonly last_updated: string | null;
    readonly last_user_content_updated: string | null;
};

export type WalkthroughRejection = {
    reason: string;
};

export type WalkthroughStat = {
    video_and_text: number;
    video: number;
    text: number;
    none: number;
};

/**
 * * `l` - Link
 * * `t` - Text
 */
export type WalkthroughTypeEnum = 'l' | 't';

export type Winner = {
    place: number;
    user: UserNested;
};

export type AuditLogListingWritable = {
    object_id: string;
    object_name: string;
    change_type: ChangeTypeEnum;
    changes: unknown;
    meta: unknown;
    is_action_required?: boolean;
};

export type AwardRecipientWritable = {
    [key: string]: unknown;
};

export type AwardSpecWritable = {
    code: string;
    title: string;
    description: string;
    tier: number;
    can_be_removed: boolean;
};

export type ConfigWritable = {
    countries: Array<CountryListing>;
    tags: Array<TagListingWritable>;
    genres: Array<GenreListingWritable>;
    engines: Array<EngineListingWritable>;
    difficulties: Array<LevelDifficultyListingWritable>;
    durations: Array<LevelDurationListingWritable>;
    rating_questions: Array<RatingTemplateQuestionWritable>;
    limits: GlobalLimits;
    stats: GlobalStatsWritable;
    global_message?: string | null;
};

export type EngineListingWritable = {
    name: string;
    position?: number;
};

export type EngineNestedWritable = {
    name: string;
};

export type EventDetailsWritable = {
    name: string;
    subtitle?: string | null;
    year?: number | null;
};

export type EventListingWritable = {
    name: string;
    subtitle?: string | null;
    year?: number | null;
};

export type FeaturedLevelListingWritable = {
    feature_type: FeatureTypeEnum;
};

export type FeaturedLevelsWritable = {
    new_release: FeaturedLevelListingWritable;
    monthly_hidden_gem: FeaturedLevelListingWritable;
    level_of_the_day: FeaturedLevelListingWritable;
    best_in_genre: FeaturedLevelListingWritable;
};

export type GenreListingWritable = {
    name: string;
    description: string;
};

export type GenreNestedWritable = {
    name: string;
};

export type GlobalStatsWritable = {
    total_levels: number;
    total_ratings: number;
    total_reviews: number;
    total_walkthroughs: number;
    total_downloads: number;
    ratings: Array<RatingStatWritable>;
    walkthroughs: WalkthroughStat;
};

export type LevelDetailsWritable = {
    name: string;
    description: string;
    engine_id: number;
    duration_id: number;
    difficulty_id: number;
    genre_ids: Array<number>;
    tag_ids: Array<number>;
    author_ids: Array<number>;
    external_links?: Array<LevelExternalLinkWritable>;
    cover_id: number;
    screenshot_ids: Array<number>;
    file_id: number;
    trle_id?: number | null;
};

export type LevelDifficultyListingWritable = {
    name: string;
    position: number;
};

export type LevelDifficultyNestedWritable = {
    name: string;
};

export type LevelDurationListingWritable = {
    name: string;
    position: number;
};

export type LevelDurationNestedWritable = {
    name: string;
};

export type LevelExternalLinkWritable = {
    position: number;
    url: string;
    link_type: LinkTypeEnum;
};

export type LevelFileWritable = {
    version: number;
};

export type LevelListingWritable = {
    name: string;
    description?: string | null;
    engine_id: number;
    duration_id: number;
    difficulty_id: number;
    genre_ids: Array<number>;
    tag_ids: Array<number>;
    author_ids: Array<number>;
    external_links?: Array<LevelExternalLinkWritable>;
};

export type LevelNestedWritable = {
    name: string;
};

export type LevelScreenshotWritable = {
    position?: number;
};

export type NewsDetailsWritable = {
    subject?: string | null;
    text?: string | null;
};

export type NewsListingWritable = {
    subject?: string | null;
    text?: string | null;
};

export type PaginatedAuditLogListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<AuditLogListingWritable>;
    disable_paging: boolean;
};

export type PaginatedAwardRecipientListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<AwardRecipientWritable>;
    disable_paging: boolean;
};

export type PaginatedEngineListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<EngineListingWritable>;
    disable_paging: boolean;
};

export type PaginatedEventListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<EventListingWritable>;
    disable_paging: boolean;
};

export type PaginatedGenreListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<GenreListingWritable>;
    disable_paging: boolean;
};

export type PaginatedLevelListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<LevelListingWritable>;
    disable_paging: boolean;
};

export type PaginatedNewsListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<NewsListingWritable>;
    disable_paging: boolean;
};

export type PaginatedPlaylistItemListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<PlaylistItemWritable>;
    disable_paging: boolean;
};

export type PaginatedRatingListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<RatingListingWritable>;
    disable_paging: boolean;
};

export type PaginatedReviewListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<ReviewListingWritable>;
    disable_paging: boolean;
};

export type PaginatedTagListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<TagListingWritable>;
    disable_paging: boolean;
};

export type PaginatedUserListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<UserListingWritable>;
    disable_paging: boolean;
};

export type PaginatedWalkthroughListingListWritable = {
    current_page: number;
    last_page: number;
    total_count: number;
    items_on_page: number;
    next: string | null;
    previous: string | null;
    results: Array<WalkthroughListingWritable>;
    disable_paging: boolean;
};

export type PatchedLevelDetailsWritable = {
    name?: string;
    description?: string;
    engine_id?: number;
    duration_id?: number;
    difficulty_id?: number;
    genre_ids?: Array<number>;
    tag_ids?: Array<number>;
    author_ids?: Array<number>;
    external_links?: Array<LevelExternalLinkWritable>;
    cover_id?: number;
    screenshot_ids?: Array<number>;
    file_id?: number;
    trle_id?: number | null;
};

export type PatchedNewsDetailsWritable = {
    subject?: string | null;
    text?: string | null;
};

export type PatchedPlaylistItemWritable = {
    level_id?: number;
    status?: PlaylistItemStatusEnum;
};

export type PatchedRatingDetailsWritable = {
    answer_ids?: Array<number>;
    level_id?: number;
};

export type PatchedReviewDetailsWritable = {
    text?: string;
    is_hidden?: boolean;
    rejection_reason?: string | null;
    upvote_count?: number;
    downvote_count?: number;
    level_id?: number;
};

export type PatchedTagDetailsWritable = {
    name?: string;
};

export type PatchedUserDetailsWritable = {
    username?: string;
    first_name?: string;
    last_name?: string;
    bio?: string;
    email?: string;
    country_code?: string | null;
    website_url?: string | string | null;
    donation_url?: string | string | null;
    old_password?: string;
    password?: string;
    picture_id?: number | null;
    settings?: UserSettings;
};

export type PatchedWalkthroughDetailsWritable = {
    walkthrough_type?: WalkthroughTypeEnum;
    text?: string;
    level_id?: number;
};

export type PlaylistItemWritable = {
    level_id: number;
    status: PlaylistItemStatusEnum;
};

export type RatingAuthorWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
    rated_level_count?: number;
};

export type RatingClassNestedWritable = {
    name: string;
    position?: number | null;
};

export type RatingDetailsWritable = {
    answer_ids: Array<number>;
    level_id: number;
};

export type RatingListingWritable = {
    [key: string]: unknown;
};

export type RatingStatWritable = {
    rating_class: RatingClassNestedWritable;
    level_count: number;
};

export type RatingTemplateAnswerWritable = {
    position: number;
    answer_text: string;
};

export type RatingTemplateQuestionWritable = {
    position: number;
    question_text: string;
    category?: string | null;
};

export type ReviewAuthorWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
    reviewed_level_count?: number;
};

export type ReviewDetailsWritable = {
    text: string;
    is_hidden?: boolean;
    rejection_reason?: string | null;
    upvote_count?: number;
    downvote_count?: number;
    level_id: number;
};

export type ReviewListingWritable = {
    text?: string | null;
    is_hidden?: boolean;
    rejection_reason?: string | null;
    upvote_count?: number;
    downvote_count?: number;
};

export type TagDetailsWritable = {
    name: string;
};

export type TagListingWritable = {
    name: string;
};

export type TagNestedWritable = {
    name: string;
};

export type UploadedFileDetailsWritable = {
    content?: string | null;
    upload_type: UploadTypeEnum;
};

export type UploadedFileNestedWritable = {
    content?: string | null;
    upload_type: UploadTypeEnum;
};

export type UserAwardWritable = {
    position?: number;
    code: string;
    title: string;
    description: string;
    tier?: number | null;
};

export type UserCompletePasswordResetWritable = {
    password: string;
    token: string;
};

export type UserDetailsWritable = {
    username: string;
    first_name?: string;
    last_name?: string;
    bio?: string;
    email: string;
    country_code?: string | null;
    website_url?: string | string | null;
    donation_url?: string | string | null;
    old_password?: string;
    password: string;
    picture_id?: number | null;
    settings?: UserSettings;
};

export type UserListingWritable = {
    username: string;
    first_name?: string;
    last_name?: string;
    bio?: string;
};

export type UserNestedWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
};

export type WalkthroughAuthorWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
};

export type WalkthroughDetailsWritable = {
    walkthrough_type: WalkthroughTypeEnum;
    text: string;
    level_id: number;
};

export type WalkthroughListingWritable = {
    walkthrough_type: WalkthroughTypeEnum;
    text: string;
};

export type WinnerWritable = {
    place: number;
};

export type AuditlogsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/auditlogs/';
};

export type AuditlogsListResponses = {
    200: PaginatedAuditLogListingList;
};

export type AuditlogsListResponse = AuditlogsListResponses[keyof AuditlogsListResponses];

export type AuthTokenCreateData = {
    body: TokenObtainPair;
    path?: never;
    query?: never;
    url: '/api/auth/token/';
};

export type AuthTokenCreateResponses = {
    200: TokenObtainPair;
};

export type AuthTokenCreateResponse = AuthTokenCreateResponses[keyof AuthTokenCreateResponses];

export type AuthTokenLogoutCreateData = {
    body: TokenBlacklist;
    path?: never;
    query?: never;
    url: '/api/auth/token/logout/';
};

export type AuthTokenLogoutCreateResponses = {
    200: TokenBlacklist;
};

export type AuthTokenLogoutCreateResponse = AuthTokenLogoutCreateResponses[keyof AuthTokenLogoutCreateResponses];

export type AuthTokenRefreshCreateData = {
    body: TokenRefresh;
    path?: never;
    query?: never;
    url: '/api/auth/token/refresh/';
};

export type AuthTokenRefreshCreateResponses = {
    200: TokenRefresh;
};

export type AuthTokenRefreshCreateResponse = AuthTokenRefreshCreateResponses[keyof AuthTokenRefreshCreateResponses];

export type AwardSpecsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/award_specs/';
};

export type AwardSpecsListResponses = {
    200: Array<AwardSpec>;
};

export type AwardSpecsListResponse = AwardSpecsListResponses[keyof AwardSpecsListResponses];

export type AwardSpecsRecipientsListData = {
    body?: never;
    path: {
        code: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/award_specs/{code}/recipients/';
};

export type AwardSpecsRecipientsListResponses = {
    200: PaginatedAwardRecipientList;
};

export type AwardSpecsRecipientsListResponse = AwardSpecsRecipientsListResponses[keyof AwardSpecsRecipientsListResponses];

export type ConfigListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config/';
};

export type ConfigListResponses = {
    200: Array<Config>;
};

export type ConfigListResponse = ConfigListResponses[keyof ConfigListResponses];

export type ConfigFeaturedLevelsRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config/featured_levels/';
};

export type ConfigFeaturedLevelsRetrieveResponses = {
    200: FeaturedLevels;
};

export type ConfigFeaturedLevelsRetrieveResponse = ConfigFeaturedLevelsRetrieveResponses[keyof ConfigFeaturedLevelsRetrieveResponses];

export type EventsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/events/';
};

export type EventsListResponses = {
    200: PaginatedEventListingList;
};

export type EventsListResponse = EventsListResponses[keyof EventsListResponses];

export type EventsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this event.
         */
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/';
};

export type EventsRetrieveResponses = {
    200: EventDetails;
};

export type EventsRetrieveResponse = EventsRetrieveResponses[keyof EventsRetrieveResponses];

export type LevelEnginesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/level_engines/';
};

export type LevelEnginesListResponses = {
    200: PaginatedEngineListingList;
};

export type LevelEnginesListResponse = LevelEnginesListResponses[keyof LevelEnginesListResponses];

export type LevelFilesDownloadRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this level file.
         */
        id: number;
    };
    query?: never;
    url: '/api/level_files/{id}/download/';
};

export type LevelFilesDownloadRetrieveResponses = {
    200: Blob | File;
};

export type LevelFilesDownloadRetrieveResponse = LevelFilesDownloadRetrieveResponses[keyof LevelFilesDownloadRetrieveResponses];

export type LevelGenresListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/level_genres/';
};

export type LevelGenresListResponses = {
    200: PaginatedGenreListingList;
};

export type LevelGenresListResponse = LevelGenresListResponses[keyof LevelGenresListResponses];

export type LevelGenresRetrieveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/level_genres/{id}/';
};

export type LevelGenresRetrieveResponses = {
    200: GenreListing;
};

export type LevelGenresRetrieveResponse = LevelGenresRetrieveResponses[keyof LevelGenresRetrieveResponses];

export type LevelGenresStatsListData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/level_genres/{id}/stats/';
};

export type LevelGenresStatsListResponses = {
    200: Array<GenreListing>;
};

export type LevelGenresStatsListResponse = LevelGenresStatsListResponses[keyof LevelGenresStatsListResponses];

export type LevelTagsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/level_tags/';
};

export type LevelTagsListResponses = {
    200: PaginatedTagListingList;
};

export type LevelTagsListResponse = LevelTagsListResponses[keyof LevelTagsListResponses];

export type LevelTagsCreateData = {
    body: TagDetailsWritable;
    path?: never;
    query?: never;
    url: '/api/level_tags/';
};

export type LevelTagsCreateResponses = {
    201: TagDetails;
};

export type LevelTagsCreateResponse = LevelTagsCreateResponses[keyof LevelTagsCreateResponses];

export type LevelTagsDestroyData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/level_tags/{id}/';
};

export type LevelTagsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type LevelTagsDestroyResponse = LevelTagsDestroyResponses[keyof LevelTagsDestroyResponses];

export type LevelTagsRetrieveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/level_tags/{id}/';
};

export type LevelTagsRetrieveResponses = {
    200: TagListing;
};

export type LevelTagsRetrieveResponse = LevelTagsRetrieveResponses[keyof LevelTagsRetrieveResponses];

export type LevelTagsPartialUpdateData = {
    body?: PatchedTagDetailsWritable;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/level_tags/{id}/';
};

export type LevelTagsPartialUpdateResponses = {
    200: TagDetails;
};

export type LevelTagsPartialUpdateResponse = LevelTagsPartialUpdateResponses[keyof LevelTagsPartialUpdateResponses];

export type LevelTagsUpdateData = {
    body: TagDetailsWritable;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/level_tags/{id}/';
};

export type LevelTagsUpdateResponses = {
    200: TagDetails;
};

export type LevelTagsUpdateResponse = LevelTagsUpdateResponses[keyof LevelTagsUpdateResponses];

export type LevelTagsMergeCreateData = {
    body: TagMerge;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/level_tags/{id}/merge/';
};

export type LevelTagsMergeCreateResponses = {
    200: TagDetails;
};

export type LevelTagsMergeCreateResponse = LevelTagsMergeCreateResponses[keyof LevelTagsMergeCreateResponses];

export type LevelTagsStatsListData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/level_tags/{id}/stats/';
};

export type LevelTagsStatsListResponses = {
    200: Array<TagListing>;
};

export type LevelTagsStatsListResponse = LevelTagsStatsListResponses[keyof LevelTagsStatsListResponses];

export type LevelTagsByNameRetrieveData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/level_tags/by_name/{name}/';
};

export type LevelTagsByNameRetrieveResponses = {
    200: TagDetails;
};

export type LevelTagsByNameRetrieveResponse = LevelTagsByNameRetrieveResponses[keyof LevelTagsByNameRetrieveResponses];

export type LevelsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/levels/';
};

export type LevelsListResponses = {
    200: PaginatedLevelListingList;
};

export type LevelsListResponse = LevelsListResponses[keyof LevelsListResponses];

export type LevelsCreateData = {
    body: LevelDetailsWritable;
    path?: never;
    query?: never;
    url: '/api/levels/';
};

export type LevelsCreateResponses = {
    201: LevelDetails;
};

export type LevelsCreateResponse = LevelsCreateResponses[keyof LevelsCreateResponses];

export type LevelsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this level.
         */
        id: number;
    };
    query?: never;
    url: '/api/levels/{id}/';
};

export type LevelsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type LevelsDestroyResponse = LevelsDestroyResponses[keyof LevelsDestroyResponses];

export type LevelsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this level.
         */
        id: number;
    };
    query?: never;
    url: '/api/levels/{id}/';
};

export type LevelsRetrieveResponses = {
    200: LevelDetails;
};

export type LevelsRetrieveResponse = LevelsRetrieveResponses[keyof LevelsRetrieveResponses];

export type LevelsPartialUpdateData = {
    body?: PatchedLevelDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this level.
         */
        id: number;
    };
    query?: never;
    url: '/api/levels/{id}/';
};

export type LevelsPartialUpdateResponses = {
    200: LevelDetails;
};

export type LevelsPartialUpdateResponse = LevelsPartialUpdateResponses[keyof LevelsPartialUpdateResponses];

export type LevelsUpdateData = {
    body: LevelDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this level.
         */
        id: number;
    };
    query?: never;
    url: '/api/levels/{id}/';
};

export type LevelsUpdateResponses = {
    200: LevelDetails;
};

export type LevelsUpdateResponse = LevelsUpdateResponses[keyof LevelsUpdateResponses];

export type LevelsApproveCreateData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this level.
         */
        id: number;
    };
    query?: never;
    url: '/api/levels/{id}/approve/';
};

export type LevelsApproveCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type LevelsRatingStatsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this level.
         */
        id: number;
    };
    query?: never;
    url: '/api/levels/{id}/rating_stats/';
};

export type LevelsRatingStatsRetrieveResponses = {
    200: LevelRatingStats;
};

export type LevelsRatingStatsRetrieveResponse = LevelsRatingStatsRetrieveResponses[keyof LevelsRatingStatsRetrieveResponses];

export type LevelsRejectCreateData = {
    body: LevelRejection;
    path: {
        /**
         * A unique integer value identifying this level.
         */
        id: number;
    };
    query?: never;
    url: '/api/levels/{id}/reject/';
};

export type LevelsRejectCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type NewsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/news/';
};

export type NewsListResponses = {
    200: PaginatedNewsListingList;
};

export type NewsListResponse = NewsListResponses[keyof NewsListResponses];

export type NewsCreateData = {
    body?: NewsDetailsWritable;
    path?: never;
    query?: never;
    url: '/api/news/';
};

export type NewsCreateResponses = {
    201: NewsDetails;
};

export type NewsCreateResponse = NewsCreateResponses[keyof NewsCreateResponses];

export type NewsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this news.
         */
        id: number;
    };
    query?: never;
    url: '/api/news/{id}/';
};

export type NewsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type NewsDestroyResponse = NewsDestroyResponses[keyof NewsDestroyResponses];

export type NewsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this news.
         */
        id: number;
    };
    query?: never;
    url: '/api/news/{id}/';
};

export type NewsRetrieveResponses = {
    200: NewsListing;
};

export type NewsRetrieveResponse = NewsRetrieveResponses[keyof NewsRetrieveResponses];

export type NewsPartialUpdateData = {
    body?: PatchedNewsDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this news.
         */
        id: number;
    };
    query?: never;
    url: '/api/news/{id}/';
};

export type NewsPartialUpdateResponses = {
    200: NewsDetails;
};

export type NewsPartialUpdateResponse = NewsPartialUpdateResponses[keyof NewsPartialUpdateResponses];

export type NewsUpdateData = {
    body?: NewsDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this news.
         */
        id: number;
    };
    query?: never;
    url: '/api/news/{id}/';
};

export type NewsUpdateResponses = {
    200: NewsDetails;
};

export type NewsUpdateResponse = NewsUpdateResponses[keyof NewsUpdateResponses];

export type RatingsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/ratings/';
};

export type RatingsListResponses = {
    200: PaginatedRatingListingList;
};

export type RatingsListResponse = RatingsListResponses[keyof RatingsListResponses];

export type RatingsCreateData = {
    body: RatingDetailsWritable;
    path?: never;
    query?: never;
    url: '/api/ratings/';
};

export type RatingsCreateResponses = {
    201: RatingDetails;
};

export type RatingsCreateResponse = RatingsCreateResponses[keyof RatingsCreateResponses];

export type RatingsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rating.
         */
        id: number;
    };
    query?: never;
    url: '/api/ratings/{id}/';
};

export type RatingsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type RatingsDestroyResponse = RatingsDestroyResponses[keyof RatingsDestroyResponses];

export type RatingsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this rating.
         */
        id: number;
    };
    query?: never;
    url: '/api/ratings/{id}/';
};

export type RatingsRetrieveResponses = {
    200: RatingDetails;
};

export type RatingsRetrieveResponse = RatingsRetrieveResponses[keyof RatingsRetrieveResponses];

export type RatingsPartialUpdateData = {
    body?: PatchedRatingDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this rating.
         */
        id: number;
    };
    query?: never;
    url: '/api/ratings/{id}/';
};

export type RatingsPartialUpdateResponses = {
    200: RatingDetails;
};

export type RatingsPartialUpdateResponse = RatingsPartialUpdateResponses[keyof RatingsPartialUpdateResponses];

export type RatingsUpdateData = {
    body: RatingDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this rating.
         */
        id: number;
    };
    query?: never;
    url: '/api/ratings/{id}/';
};

export type RatingsUpdateResponses = {
    200: RatingDetails;
};

export type RatingsUpdateResponse = RatingsUpdateResponses[keyof RatingsUpdateResponses];

export type ReviewsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/reviews/';
};

export type ReviewsListResponses = {
    200: PaginatedReviewListingList;
};

export type ReviewsListResponse = ReviewsListResponses[keyof ReviewsListResponses];

export type ReviewsCreateData = {
    body: ReviewDetailsWritable;
    path?: never;
    query?: never;
    url: '/api/reviews/';
};

export type ReviewsCreateResponses = {
    201: ReviewDetails;
};

export type ReviewsCreateResponse = ReviewsCreateResponses[keyof ReviewsCreateResponses];

export type ReviewsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this review.
         */
        id: number;
    };
    query?: never;
    url: '/api/reviews/{id}/';
};

export type ReviewsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ReviewsDestroyResponse = ReviewsDestroyResponses[keyof ReviewsDestroyResponses];

export type ReviewsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this review.
         */
        id: number;
    };
    query?: never;
    url: '/api/reviews/{id}/';
};

export type ReviewsRetrieveResponses = {
    200: ReviewDetails;
};

export type ReviewsRetrieveResponse = ReviewsRetrieveResponses[keyof ReviewsRetrieveResponses];

export type ReviewsPartialUpdateData = {
    body?: PatchedReviewDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this review.
         */
        id: number;
    };
    query?: never;
    url: '/api/reviews/{id}/';
};

export type ReviewsPartialUpdateResponses = {
    200: ReviewDetails;
};

export type ReviewsPartialUpdateResponse = ReviewsPartialUpdateResponses[keyof ReviewsPartialUpdateResponses];

export type ReviewsUpdateData = {
    body: ReviewDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this review.
         */
        id: number;
    };
    query?: never;
    url: '/api/reviews/{id}/';
};

export type ReviewsUpdateResponses = {
    200: ReviewDetails;
};

export type ReviewsUpdateResponse = ReviewsUpdateResponses[keyof ReviewsUpdateResponses];

export type ReviewsHideCreateData = {
    body: ReviewHide;
    path: {
        /**
         * A unique integer value identifying this review.
         */
        id: number;
    };
    query?: never;
    url: '/api/reviews/{id}/hide/';
};

export type ReviewsHideCreateResponses = {
    200: ReviewHide;
};

export type ReviewsHideCreateResponse = ReviewsHideCreateResponses[keyof ReviewsHideCreateResponses];

export type ReviewsVoteCreateData = {
    body: ReviewVote;
    path: {
        /**
         * A unique integer value identifying this review.
         */
        id: number;
    };
    query?: never;
    url: '/api/reviews/{id}/vote/';
};

export type ReviewsVoteCreateResponses = {
    200: ReviewListing;
};

export type ReviewsVoteCreateResponse = ReviewsVoteCreateResponses[keyof ReviewsVoteCreateResponses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];

export type UploadsCreateData = {
    body: UploadedFileDetailsWritable;
    path?: never;
    query?: never;
    url: '/api/uploads/';
};

export type UploadsCreateResponses = {
    201: UploadedFileDetails;
};

export type UploadsCreateResponse = UploadsCreateResponses[keyof UploadsCreateResponses];

export type UploadsRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/uploads/{id}/';
};

export type UploadsRetrieveResponses = {
    200: UploadedFileDetails;
};

export type UploadsRetrieveResponse = UploadsRetrieveResponses[keyof UploadsRetrieveResponses];

export type UploadsFileRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/uploads/{id}/file/';
};

export type UploadsFileRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/users/';
};

export type UsersListResponses = {
    200: PaginatedUserListingList;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: UserDetailsWritable;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersCreateResponses = {
    201: UserDetails;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: UserDetails;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUserDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: UserDetails;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: UserDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersUpdateResponses = {
    200: UserDetails;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersActivateCreateData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/activate/';
};

export type UsersActivateCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UsersBanCreateData = {
    body: UserBan;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/ban/';
};

export type UsersBanCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UsersDeactivateCreateData = {
    body: UserBan;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/deactivate/';
};

export type UsersDeactivateCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UsersUnbanCreateData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/unban/';
};

export type UsersUnbanCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UsersPlaylistListData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/users/{user_id}/playlist/';
};

export type UsersPlaylistListResponses = {
    200: PaginatedPlaylistItemList;
};

export type UsersPlaylistListResponse = UsersPlaylistListResponses[keyof UsersPlaylistListResponses];

export type UsersPlaylistCreateData = {
    body: PlaylistItemWritable;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}/playlist/';
};

export type UsersPlaylistCreateResponses = {
    201: PlaylistItem;
};

export type UsersPlaylistCreateResponse = UsersPlaylistCreateResponses[keyof UsersPlaylistCreateResponses];

export type UsersPlaylistDestroyData = {
    body?: never;
    path: {
        id: number;
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}/playlist/{id}/';
};

export type UsersPlaylistDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersPlaylistDestroyResponse = UsersPlaylistDestroyResponses[keyof UsersPlaylistDestroyResponses];

export type UsersPlaylistPartialUpdateData = {
    body?: PatchedPlaylistItemWritable;
    path: {
        id: number;
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}/playlist/{id}/';
};

export type UsersPlaylistPartialUpdateResponses = {
    200: PlaylistItem;
};

export type UsersPlaylistPartialUpdateResponse = UsersPlaylistPartialUpdateResponses[keyof UsersPlaylistPartialUpdateResponses];

export type UsersPlaylistUpdateData = {
    body: PlaylistItemWritable;
    path: {
        id: number;
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}/playlist/{id}/';
};

export type UsersPlaylistUpdateResponses = {
    200: PlaylistItem;
};

export type UsersPlaylistUpdateResponse = UsersPlaylistUpdateResponses[keyof UsersPlaylistUpdateResponses];

export type UsersPlaylistByLevelIdRetrieveData = {
    body?: never;
    path: {
        level_id: number;
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}/playlist/by_level_id/{level_id}/';
};

export type UsersPlaylistByLevelIdRetrieveResponses = {
    200: PlaylistItem;
};

export type UsersPlaylistByLevelIdRetrieveResponse = UsersPlaylistByLevelIdRetrieveResponses[keyof UsersPlaylistByLevelIdRetrieveResponses];

export type UsersPlaylistImportCreateData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}/playlist/import/';
};

export type UsersPlaylistImportCreateResponses = {
    200: PlaylistImportResult;
};

export type UsersPlaylistImportCreateResponse = UsersPlaylistImportCreateResponses[keyof UsersPlaylistImportCreateResponses];

export type UsersByUsernameRetrieveData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/api/users/by_username/{username}/';
};

export type UsersByUsernameRetrieveResponses = {
    200: UserDetails;
};

export type UsersByUsernameRetrieveResponse = UsersByUsernameRetrieveResponses[keyof UsersByUsernameRetrieveResponses];

export type UsersCompletePasswordResetCreateData = {
    body: UserCompletePasswordResetWritable;
    path?: never;
    query?: never;
    url: '/api/users/complete_password_reset/';
};

export type UsersCompletePasswordResetCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UsersConfirmEmailCreateData = {
    body: UserConfirmEmail;
    path?: never;
    query?: never;
    url: '/api/users/confirm_email/';
};

export type UsersConfirmEmailCreateResponses = {
    200: UserDetails;
};

export type UsersConfirmEmailCreateResponse = UsersConfirmEmailCreateResponses[keyof UsersConfirmEmailCreateResponses];

export type UsersMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/';
};

export type UsersMeRetrieveResponses = {
    200: UserDetails;
};

export type UsersMeRetrieveResponse = UsersMeRetrieveResponses[keyof UsersMeRetrieveResponses];

export type UsersRequestPasswordResetCreateData = {
    body: UserRequestPasswordReset;
    path?: never;
    query?: never;
    url: '/api/users/request_password_reset/';
};

export type UsersRequestPasswordResetCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UsersResendActivationEmailCreateData = {
    body: Username;
    path?: never;
    query?: never;
    url: '/api/users/resend_activation_email/';
};

export type UsersResendActivationEmailCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type WalkthroughsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        /**
         * Which field to use when ordering the results.
         */
        sort?: string;
    };
    url: '/api/walkthroughs/';
};

export type WalkthroughsListResponses = {
    200: PaginatedWalkthroughListingList;
};

export type WalkthroughsListResponse = WalkthroughsListResponses[keyof WalkthroughsListResponses];

export type WalkthroughsCreateData = {
    body: WalkthroughDetailsWritable;
    path?: never;
    query?: never;
    url: '/api/walkthroughs/';
};

export type WalkthroughsCreateResponses = {
    201: WalkthroughDetails;
};

export type WalkthroughsCreateResponse = WalkthroughsCreateResponses[keyof WalkthroughsCreateResponses];

export type WalkthroughsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this walkthrough.
         */
        id: number;
    };
    query?: never;
    url: '/api/walkthroughs/{id}/';
};

export type WalkthroughsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type WalkthroughsDestroyResponse = WalkthroughsDestroyResponses[keyof WalkthroughsDestroyResponses];

export type WalkthroughsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this walkthrough.
         */
        id: number;
    };
    query?: never;
    url: '/api/walkthroughs/{id}/';
};

export type WalkthroughsRetrieveResponses = {
    200: WalkthroughListing;
};

export type WalkthroughsRetrieveResponse = WalkthroughsRetrieveResponses[keyof WalkthroughsRetrieveResponses];

export type WalkthroughsPartialUpdateData = {
    body?: PatchedWalkthroughDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this walkthrough.
         */
        id: number;
    };
    query?: never;
    url: '/api/walkthroughs/{id}/';
};

export type WalkthroughsPartialUpdateResponses = {
    200: WalkthroughDetails;
};

export type WalkthroughsPartialUpdateResponse = WalkthroughsPartialUpdateResponses[keyof WalkthroughsPartialUpdateResponses];

export type WalkthroughsUpdateData = {
    body: WalkthroughDetailsWritable;
    path: {
        /**
         * A unique integer value identifying this walkthrough.
         */
        id: number;
    };
    query?: never;
    url: '/api/walkthroughs/{id}/';
};

export type WalkthroughsUpdateResponses = {
    200: WalkthroughDetails;
};

export type WalkthroughsUpdateResponse = WalkthroughsUpdateResponses[keyof WalkthroughsUpdateResponses];

export type WalkthroughsApproveCreateData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this walkthrough.
         */
        id: number;
    };
    query?: never;
    url: '/api/walkthroughs/{id}/approve/';
};

export type WalkthroughsApproveCreateResponses = {
    200: WalkthroughListing;
};

export type WalkthroughsApproveCreateResponse = WalkthroughsApproveCreateResponses[keyof WalkthroughsApproveCreateResponses];

export type WalkthroughsPublishCreateData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this walkthrough.
         */
        id: number;
    };
    query?: never;
    url: '/api/walkthroughs/{id}/publish/';
};

export type WalkthroughsPublishCreateResponses = {
    200: WalkthroughListing;
};

export type WalkthroughsPublishCreateResponse = WalkthroughsPublishCreateResponses[keyof WalkthroughsPublishCreateResponses];

export type WalkthroughsRejectCreateData = {
    body: WalkthroughRejection;
    path: {
        /**
         * A unique integer value identifying this walkthrough.
         */
        id: number;
    };
    query?: never;
    url: '/api/walkthroughs/{id}/reject/';
};

export type WalkthroughsRejectCreateResponses = {
    200: WalkthroughListing;
};

export type WalkthroughsRejectCreateResponse = WalkthroughsRejectCreateResponses[keyof WalkthroughsRejectCreateResponses];
