# Generated by Django 4.0 on 2022-03-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True
                    ),
                ),
                (
                    "subject",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "text",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "News",
                "ordering": ["-created"],
                "default_permissions": [],
            },
        ),
    ]
