# Generated by Django 4.0 on 2022-03-05 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="authors",
            field=models.ManyToManyField(
                related_name="authored_news", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
