# Generated by Django 4.0.2 on 2022-09-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="authors",
        ),
    ]
