# Generated by Django 4.2.3 on 2024-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_news_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Global Message",
                "verbose_name_plural": "Global Messages",
                "default_permissions": [],
            },
        ),
    ]
