# Generated by Django 4.1.3 on 2023-03-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraward",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
