# Generated by Django 4.2.3 on 2023-09-01 22:04

from django.db import migrations


def update_awards_forward(apps, schema_editor):
    user_award_cls = apps.get_model("awards", "UserAward")
    user_award_cls.objects.filter(tier=None).update(tier=0)


def update_awards_backward(apps, schema_editor):
    user_award_cls = apps.get_model("awards", "UserAward")
    user_award_cls.objects.filter(tier=0).update(tier=None)


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0002_useraward_position"),
    ]

    operations = [
        migrations.RunPython(update_awards_forward, update_awards_backward),
    ]
