# Generated by Django 4.2.3 on 2025-05-24 20:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("awards", "0003_auto_20230901_2204"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useraward",
            unique_together={("user", "code")},
        ),
    ]
