# Generated by Django 4.0 on 2022-03-05 22:53
# pylint: disable=line-too-long

import django.core.files.storage
from django.db import migrations, models

import trcustoms.uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True
                    ),
                ),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("up", "User picture"),
                            ("lb", "Level cover image"),
                            ("ls", "Level screenshot"),
                            ("lf", "Level file"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "content",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage,
                        upload_to=trcustoms.uploads.models.UploadedFile.upload_to,
                    ),
                ),
                (
                    "md5sum",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("size", models.IntegerField()),
            ],
            options={
                "default_permissions": [],
            },
        ),
    ]
