# Generated by Django 4.0.2 on 2022-04-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("up", "User picture"),
                    ("lb", "Level cover image"),
                    ("ls", "Level screenshot"),
                    ("lf", "Level file"),
                    ("at", "Post attachment"),
                ],
                max_length=2,
            ),
        ),
    ]
