# Generated by Django 4.2.3 on 2025-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0003_alter_uploadedfile_upload_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("up", "User picture"),
                    ("lb", "Level cover image"),
                    ("ls", "Level screenshot"),
                    ("lf", "Level file"),
                    ("at", "Post attachment"),
                    ("ec", "Event cover image"),
                ],
                max_length=2,
            ),
        ),
    ]
