# Generated by Django 5.2.16 on 2026-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0004_alter_uploadedfile_upload_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="pending_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="status",
            field=models.CharField(
                choices=[("p", "Pending"), ("c", "Complete")],
                default="c",
                max_length=2,
            ),
        ),
    ]
