# Generated by Django 4.0 on 2022-03-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                ("object_name", models.CharField(max_length=64)),
                ("changes", models.JSONField()),
                ("meta", models.JSONField()),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_action_required", models.BooleanField(default=False)),
            ],
            options={
                "default_permissions": [],
            },
        ),
    ]
