# Generated by Django 4.0 on 2022-03-05 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("audit_logs", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="change_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="object_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
