# The first stage
# Build React static files

FROM node:23-alpine AS build

ARG ENVIRONMENT
ENV REACT_APP_BUILD_VERSION=${BUILD_VERSION}
ENV REACT_APP_BUILD_DATE=${BUILD_DATE}
ENV REACT_APP_ENVIRONMENT=${ENVIRONMENT}
ENV REACT_APP_HOST_SITE=${HOST_SITE}

WORKDIR /app/frontend/
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm ci

COPY ./frontend/ ./
RUN npm run build

# The second stage
# Copy React static files and start nginx
FROM nginx:stable-alpine
ARG ADMIN_DIR
COPY services/nginx/nginx_prerender_map.conf /etc/nginx/nginx_prerender_map.conf
COPY services/nginx/nginx_prerender_server.conf /etc/nginx/nginx_prerender_server.conf
COPY services/nginx/nginx_prod.conf.template /etc/nginx/nginx.conf.template
RUN envsubst '${ADMIN_DIR}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
COPY --from=build /app/frontend/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
