# The first stage
# Build React static files

FROM node:14-bullseye as build

ARG BUILD_VERSION
ARG BUILD_DATE
ENV REACT_APP_BUILD_VERSION=${BUILD_VERSION}
ENV REACT_APP_BUILD_DATE=${BUILD_DATE}

WORKDIR /app/frontend/
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm ci

COPY ./frontend/ ./
RUN npm run build

# The second stage
# Copy React static files and start nginx
FROM nginx:stable-alpine
COPY services/nginx/nginx_prerender_map.conf /etc/nginx/nginx_prerender_map.conf
COPY services/nginx/nginx_prod.conf /etc/nginx/nginx.conf
COPY --from=build /app/frontend/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
