# The first stage
# Build React static files

FROM node:22-alpine AS build

ARG ENVIRONMENT
ARG BUILD_DATE
ARG BUILD_VERSION

ENV VITE_BUILD_VERSION=${BUILD_VERSION}
ENV VITE_BUILD_DATE=${BUILD_DATE}
ENV VITE_ENVIRONMENT=${ENVIRONMENT}
ENV VITE_HOST_SITE=${HOST_SITE}

WORKDIR /app/frontend/
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm ci --include=dev

COPY ./frontend/ ./
RUN npm run build

# The second stage
# Copy React static files and start nginx
FROM nginx:stable-alpine
ARG ADMIN_DIR
COPY services/nginx/nginx_prod.conf.template /etc/nginx/nginx.conf.template
RUN envsubst '${ADMIN_DIR}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
COPY --from=build /app/frontend/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
