map $http_user_agent $social_preview_ua {
  default 0;
  "~*facebookexternalhit" 1;
  "~*twitterbot" 1;
  "~*linkedinbot" 1;
  "~*embedly" 1;
  "~*slackbot" 1;
  "~*discordbot" 1;
  "~*whatsapp" 1;
  "~*telegrambot" 1;
  "~*skypeuripreview" 1;
  "~*bitrix\\ link\\ preview" 1;
}
