# Generated by Django 3.2.6 on 2021-11-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0003_auto_20211117_2001"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="levelcategory",
            options={"verbose_name_plural": "Level categories"},
        ),
        migrations.AlterField(
            model_name="level",
            name="author_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
