# Generated by Django 3.2.6 on 2021-11-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0004_auto_20211117_2051"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LevelCategory",
            new_name="LevelGenre",
        ),
        migrations.AlterModelOptions(
            name="levelgenre",
            options={"verbose_name_plural": "Level genres"},
        ),
        migrations.RemoveField(
            model_name="level",
            name="categories",
        ),
        migrations.AddField(
            model_name="level",
            name="genres",
            field=models.ManyToManyField(to="trcustoms.LevelGenre"),
        ),
    ]
