# Generated by Django 3.2.6 on 2021-12-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0005_auto_20211124_1827"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatar",
            new_name="picture",
        ),
    ]
