# Generated by Django 3.2.6 on 2021-12-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0006_rename_avatar_user_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelfile",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="trcustoms.level",
            ),
        ),
    ]
