# Generated by Django 3.2.6 on 2021-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0008_levelfile_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelfile",
            name="version",
            field=models.IntegerField(),
        ),
    ]
