# Generated by Django 3.2.6 on 2021-12-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0011_alter_levelfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelimage",
            name="position",
            field=models.IntegerField(default=1),
        ),
    ]
