# Generated by Django 3.2.6 on 2021-12-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0012_levelimage_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="levelimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
            ),
        ),
    ]
