# Generated by Django 3.2.6 on 2021-12-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0014_auto_20211212_1730"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easy", "easy"),
                    ("medium", "medium"),
                    ("hard", "hard"),
                    ("very_hard", "very hard"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("short", "short"),
                    ("medium", "medium"),
                    ("long", "long"),
                    ("very_long", "very long"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="trle_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="trle_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
