# Generated by Django 3.2.6 on 2021-12-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0015_auto_20211218_0910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="description",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
