# Generated by Django 3.2.6 on 2021-12-18 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0016_alter_level_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="authors",
            field=models.ManyToManyField(
                related_name="levels", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
