# Generated by Django 3.2.6 on 2021-12-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0017_alter_level_authors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LevelAuthor",
        ),
    ]
