# Generated by Django 3.2.6 on 2021-12-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0018_delete_levelauthor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="levelengine",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="leveltag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="levelgenre",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Level genres",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="trle_id",
        ),
        migrations.AddField(
            model_name="user",
            name="trle_author_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="trle_reviewer_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
