# Generated by Django 3.2.6 on 2021-12-19 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0019_auto_20211219_1139"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelLegacyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True
                    ),
                ),
                ("rating_gameplay", models.IntegerField()),
                ("rating_enemies", models.IntegerField()),
                ("rating_atmosphere", models.IntegerField()),
                ("rating_lighting", models.IntegerField()),
                (
                    "text",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="trcustoms.level",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
