# Generated by Django 3.2.6 on 2021-12-19 20:38

from django.db import migrations

import trcustoms.models.user


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0020_levellegacyreview"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", trcustoms.models.user.UserManager()),
            ],
        ),
    ]
