# Generated by Django 3.2.6 on 2021-12-19 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0021_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="authors",
            field=models.ManyToManyField(
                related_name="authored_levels", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
