# Generated by Django 3.2.6 on 2021-12-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0022_alter_level_authors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="level",
            options={"ordering": ["-created"]},
        ),
    ]
