# Generated by Django 3.2.6 on 2021-12-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0023_auto_20211219_2224"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LevelImage",
            new_name="LevelMedium",
        ),
    ]
