# Generated by Django 3.2.6 on 2021-12-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0024_rename_levelimage_levelmedium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelmedium",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="trcustoms.level",
            ),
        ),
    ]
