# Generated by Django 3.2.6 on 2021-12-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0026_alter_levellegacyreview_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="levelfile",
            options={"ordering": ["version"]},
        ),
        migrations.AlterModelOptions(
            name="levelmedium",
            options={
                "ordering": ["position"],
                "verbose_name_plural": "Level media",
            },
        ),
        migrations.AddField(
            model_name="level",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="levelfile",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
    ]
