# Generated by Django 3.2.6 on 2021-12-23 23:02

from django.db import migrations


def migrate_difficulty_and_duration(apps, schema_editor):
    Level = apps.get_model("trcustoms", "Level")
    LevelDifficulty = apps.get_model("trcustoms", "LevelDifficulty")
    LevelDuration = apps.get_model("trcustoms", "LevelDuration")

    difficulty_map = {
        "easy": "Easy",
        "medium": "Medium",
        "hard": "Hard",
        "very_hard": "Very hard",
    }
    duration_map = {
        "short": "Short",
        "medium": "Medium",
        "long": "Long",
        "very_long": "Very long",
    }

    for i, (key, value) in enumerate(duration_map.items(), 1):
        level_duration, _created = LevelDuration.objects.get_or_create(
            name=value, position=i
        )
        Level.objects.filter(duration=key).update(new_duration=level_duration)

    for i, (key, value) in enumerate(difficulty_map.items(), 1):
        level_difficulty, _created = LevelDifficulty.objects.get_or_create(
            name=value, position=i
        )
        Level.objects.filter(difficulty=key).update(
            new_difficulty=level_difficulty
        )


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0028_auto_20211223_2256"),
    ]

    operations = [
        migrations.RunPython(
            migrate_difficulty_and_duration, migrations.RunPython.noop
        ),
    ]
