# Generated by Django 3.2.6 on 2021-12-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0029_auto_20211223_2302"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="level",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="level",
            name="duration",
        ),
    ]
