# Generated by Django 3.2.6 on 2021-12-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0030_auto_20211223_2319"),
    ]

    operations = [
        migrations.RenameField(
            model_name="level",
            old_name="new_difficulty",
            new_name="difficulty",
        ),
        migrations.RenameField(
            model_name="level",
            old_name="new_duration",
            new_name="duration",
        ),
    ]
