# Generated by Django 3.2.6 on 2022-01-01 15:56

import django.db.models.deletion
from django.db import migrations, models


def migrate_last_level_file(apps, schema_editor):
    Level = apps.get_model("trcustoms", "Level")
    for level in Level.objects.all():
        level.last_file = level.files.order_by("-version").first()
        level.save()


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0031_auto_20211223_2324"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="last_file",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="trcustoms.levelfile",
            ),
        ),
        migrations.RunPython(
            migrate_last_level_file, migrations.RunPython.noop
        ),
    ]
