# Generated by Django 3.2.6 on 2022-01-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0032_level_last_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="level",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
