# Generated by Django 3.2.6 on 2022-01-03 13:39
import hashlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import trcustoms.models.uploaded_file

UPLOAD_TO = trcustoms.models.uploaded_file.UploadedFile.upload_to


def get_md5_from_file_field(file_field) -> str:
    md5 = hashlib.md5()
    for chunk in file_field.chunks():
        md5.update(chunk)
    return md5.hexdigest()


def migrate_files(apps, schema_editor):
    LevelFile = apps.get_model("trcustoms", "LevelFile")
    LevelMedium = apps.get_model("trcustoms", "LevelMedium")
    UploadedFile = apps.get_model("trcustoms", "UploadedFile")
    User = apps.get_model("trcustoms", "User")

    def migrate_uploaded_file(
        instance, upload_type: str, source_attr: str, target_attr: str
    ) -> None:
        source_field = getattr(instance, source_attr)
        if not source_field:
            return
        md5sum = get_md5_from_file_field(source_field)
        uploaded_file, _created = UploadedFile.objects.get_or_create(
            md5sum=md5sum,
            defaults=dict(
                upload_type=upload_type,
                content=source_field,
                size=source_field.size,
                md5sum=md5sum,
            ),
        )
        setattr(instance, target_attr, uploaded_file)
        instance.save()

    for user in User.objects.all().order_by("-id"):
        migrate_uploaded_file(user, "up", "picture", "new_picture")

    for level_medium in LevelMedium.objects.all().order_by("-id"):
        migrate_uploaded_file(level_medium, "ls", "image", "file")

    for level_file in LevelFile.objects.all().order_by("-id"):
        migrate_uploaded_file(level_file, "lf", "file", "new_file")


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0033_level_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True
                    ),
                ),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("up", "User picture"),
                            ("lb", "Level banner"),
                            ("ls", "Level screenshot"),
                            ("lf", "Level file"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "content",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=UPLOAD_TO,
                    ),
                ),
                (
                    "md5sum",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("size", models.IntegerField()),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="levelfile",
            name="new_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trcustoms.uploadedfile",
            ),
        ),
        migrations.AddField(
            model_name="levelmedium",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trcustoms.uploadedfile",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="new_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trcustoms.uploadedfile",
            ),
        ),
        migrations.RunPython(migrate_files, migrations.RunPython.noop),
    ]
