# Generated by Django 3.2.6 on 2022-01-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0034_auto_20220103_1339"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="levelfile",
            name="file",
        ),
        migrations.RemoveField(
            model_name="levelfile",
            name="size",
        ),
        migrations.RemoveField(
            model_name="levelmedium",
            name="image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="picture",
        ),
    ]
