# Generated by Django 3.2.6 on 2022-01-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0035_auto_20220103_1547"),
    ]

    operations = [
        migrations.RenameField(
            model_name="levelfile",
            old_name="new_file",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="new_picture",
            new_name="picture",
        ),
    ]
