# Generated by Django 3.2.6 on 2022-01-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0038_levelgenre_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelgenre",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
