# Generated by Django 3.2.6 on 2022-01-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0039_alter_levelgenre_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="level",
            old_name="banner",
            new_name="cover",
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("up", "User picture"),
                    ("lb", "Level cover image"),
                    ("ls", "Level screenshot"),
                    ("lf", "Level file"),
                ],
                max_length=2,
            ),
        ),
    ]
