# Generated by Django 3.2.6 on 2022-01-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0042_snapshot"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LevelMedium",
            new_name="LevelScreenshot",
        ),
    ]
