# Generated by Django 4.0 on 2022-01-19 15:00

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0045_remove_leveldownload_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True
                    ),
                ),
                ("url", models.URLField(max_length=256)),
                ("position", models.IntegerField()),
                (
                    "link_type",
                    models.CharField(
                        choices=[("sh", "Showcase"), ("ma", "Main")],
                        max_length=2,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_links",
                        to="trcustoms.level",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="levelexternallink",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("level"),
                django.db.models.functions.text.Lower("url"),
                name="level_external_link_unique",
            ),
        ),
    ]
