# Generated by Django 4.0 on 2022-01-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0047_level_disapproval_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="level",
            old_name="disapproval_reason",
            new_name="rejection_reason",
        ),
    ]
