# Generated by Django 4.0 on 2022-01-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0049_reviewtemplatequestion_reviewtemplateanswer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LevelLegacyReview",
            new_name="LevelReview",
        ),
    ]
