# Generated by Django 4.0 on 2022-01-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0050_rename_levellegacyreview_levelreview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="levelreview",
            old_name="rating_atmosphere",
            new_name="trle_rating_atmosphere",
        ),
        migrations.RenameField(
            model_name="levelreview",
            old_name="rating_enemies",
            new_name="trle_rating_enemies",
        ),
        migrations.RenameField(
            model_name="levelreview",
            old_name="rating_gameplay",
            new_name="trle_rating_gameplay",
        ),
        migrations.RenameField(
            model_name="levelreview",
            old_name="rating_lighting",
            new_name="trle_rating_lighting",
        ),
        migrations.AddField(
            model_name="levelreview",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("le", "Legacy (TRLE.net)"),
                    ("mo", "Modern (TRCustoms)"),
                ],
                default="le",
                max_length=2,
            ),
        ),
    ]
