# Generated by Django 4.0 on 2022-01-24 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0052_levelreviewanswer"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("le", "Level"), ("re", "Review")],
                        max_length=2,
                    ),
                ),
                ("position", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=30)),
                ("min_rating_count", models.IntegerField()),
                (
                    "min_rating_average",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "max_rating_average",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rating classes",
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="level",
            name="rating_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trcustoms.ratingclass",
            ),
        ),
        migrations.AddField(
            model_name="levelreview",
            name="rating_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trcustoms.ratingclass",
            ),
        ),
    ]
