# Generated by Django 4.0 on 2022-01-27 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0053_ratingclass_level_rating_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelreview",
            name="trle_rating_atmosphere",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="levelreview",
            name="trle_rating_enemies",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="levelreview",
            name="trle_rating_gameplay",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="levelreview",
            name="trle_rating_lighting",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewtemplateanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="trcustoms.reviewtemplatequestion",
            ),
        ),
    ]
