# Generated by Django 4.0 on 2022-01-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "trcustoms",
            "0054_alter_levelreview_trle_rating_atmosphere_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewtemplateanswer",
            options={"ordering": ["question__position", "position"]},
        ),
        migrations.AlterModelOptions(
            name="reviewtemplatequestion",
            options={"ordering": ["position"]},
        ),
    ]
