# Generated by Django 4.0 on 2022-02-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "trcustoms",
            "0057_auditlog_alter_levelreview_options_delete_snapshot",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlog",
            old_name="description",
            new_name="changes",
        ),
    ]
