# Generated by Django 4.0 on 2022-02-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0058_rename_description_auditlog_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ban_reason",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
