# Generated by Django 4.0 on 2022-02-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0059_user_ban_reason_user_is_banned"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlog",
            old_name="is_reviewed",
            new_name="is_action_required",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="previous",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="reviewer",
        ),
    ]
