# Generated by Django 4.0 on 2022-02-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trcustoms",
            "0060_rename_is_reviewed_auditlog_is_action_required_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="meta",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
    ]
