# Generated by Django 4.0 on 2022-02-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0061_auditlog_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_pending_activation",
            field=models.BooleanField(default=False),
        ),
    ]
