# Generated by Django 4.0 on 2022-02-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0062_user_is_pending_activation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("edit_levels", "Can edit levels"),
                    ("edit_reviews", "Can edit reviews"),
                    ("edit_tags", "Can edit tags"),
                    ("edit_users", "Can edit users"),
                    ("list_users", "Can list users"),
                    ("review_audit_logs", "Can review audit logs"),
                    ("review_levels", "Can review levels"),
                    ("upload_levels", "Can upload levels"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
