# Generated by Django 4.0 on 2022-02-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0063_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="level",
            options={"default_permissions": [], "ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="leveldifficulty",
            options={
                "default_permissions": [],
                "ordering": ["position"],
                "verbose_name_plural": "Level difficulties",
            },
        ),
        migrations.AlterModelOptions(
            name="levelduration",
            options={"default_permissions": [], "ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="levelengine",
            options={"default_permissions": [], "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="levelexternallink",
            options={
                "default_permissions": [],
                "ordering": ["level", "position"],
            },
        ),
        migrations.AlterModelOptions(
            name="levelfile",
            options={"default_permissions": [], "ordering": ["version"]},
        ),
        migrations.AlterModelOptions(
            name="levelgenre",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "verbose_name_plural": "Level genres",
            },
        ),
        migrations.AlterModelOptions(
            name="levelreview",
            options={"default_permissions": [], "ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="levelscreenshot",
            options={"default_permissions": [], "ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="leveltag",
            options={"default_permissions": [], "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="ratingclass",
            options={
                "default_permissions": [],
                "ordering": ["position"],
                "verbose_name_plural": "Rating classes",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewtemplateanswer",
            options={
                "default_permissions": [],
                "ordering": ["question__position", "position"],
            },
        ),
        migrations.AlterModelOptions(
            name="reviewtemplatequestion",
            options={"default_permissions": [], "ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": [],
                "permissions": [
                    ("edit_levels", "Can edit levels"),
                    ("edit_reviews", "Can edit reviews"),
                    ("edit_tags", "Can edit tags"),
                    ("edit_users", "Can edit users"),
                    ("list_users", "Can list users"),
                    ("review_audit_logs", "Can review audit logs"),
                    ("review_levels", "Can review levels"),
                    ("upload_levels", "Can upload levels"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
