# Generated by Django 4.0 on 2022-02-15 10:29

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models

import trcustoms.models.uploaded_file


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0065_auto_20220213_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="content",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage,
                upload_to=(
                    trcustoms.models.uploaded_file.UploadedFile.upload_to
                ),
            ),
        ),
        migrations.CreateModel(
            name="FeaturedLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("gem", "Monthly hidden gem"),
                            ("lod", "Level of the day"),
                            ("big", "Best in genre"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="trcustoms.level",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
