# Generated by Django 4.0 on 2022-02-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0066_alter_uploadedfile_content_featuredlevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredlevel",
            name="chosen_genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="trcustoms.levelgenre",
            ),
        ),
    ]
