# Generated by Django 4.0 on 2022-02-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trcustoms", "0068_country_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
