# Generated by Django 4.0 on 2022-03-05 22:53

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("uploads", "0001_initial"),
        ("levels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelscreenshot",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="uploads.uploadedfile",
            ),
        ),
        migrations.AddField(
            model_name="levelscreenshot",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screenshots",
                to="levels.level",
            ),
        ),
        migrations.AddField(
            model_name="levelfile",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="uploads.uploadedfile",
            ),
        ),
        migrations.AddField(
            model_name="levelfile",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="levels.level",
            ),
        ),
        migrations.AddField(
            model_name="levelexternallink",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_links",
                to="levels.level",
            ),
        ),
        migrations.AddConstraint(
            model_name="levelduration",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="duration_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="leveldifficulty",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="difficulty_name_unique",
            ),
        ),
    ]
