# Generated by Django 4.0.2 on 2022-04-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_rename_leveltag_tag"),
        ("levels", "0006_alter_featuredlevel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tags.Tag"),
        ),
    ]
