# Generated by Django 4.0.2 on 2022-07-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("levels", "0007_alter_level_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
