# Generated by Django 4.0.2 on 2022-07-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("levels", "0008_alter_level_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
