# Generated by Django 4.0.2 on 2022-07-07 14:47

from django.db import migrations


def update_levels_forward(apps, schema_editor):
    Level = apps.get_model("levels", "Level")
    for level in Level.objects.iterator():
        level.review_count = level.reviews.count()
        level.save(update_fields=["review_count"])


class Migration(migrations.Migration):
    dependencies = [
        ("levels", "0009_level_review_count"),
    ]

    operations = [
        migrations.RunPython(update_levels_forward, migrations.RunPython.noop),
    ]
