# Generated by Django 4.2.3 on 2023-08-10 13:42

from django.db import migrations, models

REPLACEMENTS = [
    ("new", "new_release"),
    ("gem", "monthly_hidden_gem"),
    ("big", "best_in_genre"),
    ("lod", "level_of_the_day"),
]


def update_forward(apps, schema_editor):
    featured_level_cls = apps.get_model("levels", "FeaturedLevel")
    for from_, to in REPLACEMENTS:
        featured_level_cls.objects.filter(feature_type=from_).update(
            feature_type=to
        )


def update_backward(apps, schema_editor):
    featured_level_cls = apps.get_model("levels", "FeaturedLevel")
    for from_, to in REPLACEMENTS:
        featured_level_cls.objects.filter(feature_type=to).update(
            feature_type=from_
        )


class Migration(migrations.Migration):
    dependencies = [
        ("levels", "0014_auto_20230509_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredlevel",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("new_release", "New release"),
                    ("monthly_hidden_gem", "Monthly hidden gem"),
                    ("level_of_the_day", "Level of the day"),
                    ("best_in_genre", "Best in genre"),
                ],
                max_length=24,
            ),
        ),
        migrations.RunPython(update_forward, update_backward),
    ]
