# Generated by Django 4.2.3 on 2024-11-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("levels", "0015_alter_featuredlevel_feature_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="last_user_content_updated",
            field=models.DateTimeField(null=True),
        ),
    ]
