# Generated by Django 4.2.3 on 2024-11-12 12:21

from django.db import migrations


def update_levels_forward(apps, schema_editor):
    batch_size = 1000
    Level = apps.get_model("levels", "Level")

    qs = Level.objects.all().values_list("id", "last_file__created")
    while True:
        batch = list(qs[:batch_size])
        if not batch:
            break

        update_list = [
            Level(id=id, last_user_content_updated=last_file_created)
            for id, last_file_created in batch
        ]
        Level.objects.bulk_update(update_list, ["last_user_content_updated"])
        qs = qs[batch_size:]


class Migration(migrations.Migration):
    dependencies = [
        ("levels", "0016_level_last_user_content_updated"),
    ]

    operations = [
        migrations.RunPython(update_levels_forward, migrations.RunPython.noop),
    ]
