# Generated by Django 4.0 on 2022-03-05 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("levels", "0003_initial"),
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LevelGenre",
            new_name="Genre",
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "verbose_name_plural": "Genres",
            },
        ),
    ]
