# Generated by Django 4.0 on 2022-03-05 22:53

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("levels", "0003_initial"),
        ("common", "0001_initial"),
        ("reviews", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelreview",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewed_levels",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="levelreview",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="levels.level",
            ),
        ),
        migrations.AddField(
            model_name="levelreview",
            name="rating_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.ratingclass",
            ),
        ),
        migrations.AddConstraint(
            model_name="levelreview",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("level"),
                django.db.models.expressions.F("author"),
                name="review_level_author_unique",
            ),
        ),
    ]
