# Generated by Django 4.1.3 on 2023-03-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelreview",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
