# Generated by Django 4.2.3 on 2023-07-09 23:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("levels", "0014_auto_20230509_1033"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0002_alter_country_options"),
        ("reviews", "0004_auto_20230313_1706"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LevelReview",
            new_name="Review",
        ),
    ]
