# Generated by Django 4.2.3 on 2024-11-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_rename_levelreview_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="last_user_content_updated",
            field=models.DateTimeField(null=True),
        ),
    ]
