# Generated by Django 4.2.3 on 2024-11-12 12:16

from datetime import datetime, timezone

from django.db import migrations


def update_reviews_forward(apps, schema_editor):
    batch_size = 1000
    Review = apps.get_model("reviews", "Review")

    qs = Review.objects.all().values_list("id", "last_updated", "created")
    while True:
        batch = list(qs[:batch_size])
        if not batch:
            break

        update_list = [
            Review(
                id=id,
                last_user_content_updated=(
                    last_updated
                    if created >= datetime(2022, 4, 1, tzinfo=timezone.utc)
                    else created
                ),
            )
            for id, last_updated, created in batch
        ]
        Review.objects.bulk_update(update_list, ["last_user_content_updated"])
        qs = qs[batch_size:]


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_review_last_user_content_updated"),
    ]

    operations = [
        migrations.RunPython(
            update_reviews_forward, migrations.RunPython.noop
        ),
    ]
