# Generated by Django 4.2.3 on 2026-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_review_votes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reviewvote",
            name="review_vote_review_user_unique",
        ),
        migrations.AddConstraint(
            model_name="reviewvote",
            constraint=models.UniqueConstraint(
                models.F("review"),
                models.F("user"),
                name="review_vote_review_user_unique",
            ),
        ),
    ]
