# Generated by Django 4.2.3 on 2026-05-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reviews",
            "0010_remove_reviewvote_review_vote_review_user_unique_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
