name: Deploy production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build production
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: just update-prod
